server:
  port: 8084
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
spring:
  config:
    import: optional:file:.env[.properties]  # .env import
  messages:
    basename: message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/Needy_Care_System?characterEncoding=utf8
        username: smuser
        password: ENC(m90iLjAYPAsMSYEMNfP84Q==)
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: ENC(m90iLjAYPAsMSYEMNfP84Q==)
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
      api-key: ENC(DIrd78xrB30lc2q7A5pW1OwT8+V5LbMcVryz5BbtbHMWa1zwwF6oDzxZGvWb/USsdjDccGQJV+Mx1IOfWiPO5rVG4TYWUuLDXM3U6h08yyAOAy3P2tas2v9yTLZvd9obwh3zcuT6gedYUhugwCdL/EoBq/Hsg01M9ENgrKPIfAeuFHOTu9eqEWMEAzNiPuD9l+4yU8WjNqff698QGXOfHd/nT6yKrVvgXtgaZtbBehs=)
      chat:
        options:
          model: gpt-4o
          temperature: 0.1
          max-tokens: 1000

mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

app:
  url:
    websocketurl: https://192.168.1.6:8443/
  dir:
    imgsdir: file:///C:/smjava/Needy_Care_System/imgs/     # 화면 출력 용
    uploadimgsdir: C:/smjava/Needy_Care_System/imgs/    # 파일 Write 용
    logsdir: file:///C:/smjava/Needy_Care_System/logs/    # logs 화면 출력용
    logsdirRead : C:/smjava/Needy_Care_System/logs/ #
  key:
    skey: ${MY_KEY}
    algo: PBEWithMD5AndDES
    wkey: ENC(KpenOyMjgFsfI5Y63m7CO843NZ1e3rD/qFoI4ac76xcGcyFgzGi1lv128RRgkaY4lbwmKXJnH086MRn/OqV1iN4tR7FSVOVyOhrqjDHW57A226jVu9Q2oq+VjFBCurrdQF2ECJ+XlWESrLtT8BzUzA==)
    owkey: ENC(1n0CubQdrW/QjB/ed6/Y348zgr3A0CgdIGr546KvjqzbQapHn8dt3GMRT8KZxn+q)
